package org.eclipse.imp.presentation.parser;

public interface PSPParsersym {
    public final static int
      TK_ARROW = 22,
      TK_LEFTBRACE = 2,
      TK_RIGHTBRACE = 3,
      TK_LEFTPAREN = 23,
      TK_RIGHTPAREN = 24,
      TK_EQUAL = 5,
      TK_PLUS = 37,
      TK_MINUS = 38,
      TK_TIMES = 25,
      TK_SEMICOLON = 4,
      TK_DOT = 13,
      TK_COMMA = 14,
      TK_BOLD = 26,
      TK_BOOLEAN = 10,
      TK_CASE = 27,
      TK_COLOR = 6,
      TK_EXTENDS = 28,
      TK_FOLDABLE = 15,
      TK_FONT = 7,
      TK_ICON = 8,
      TK_IMPORT = 29,
      TK_INT = 11,
      TK_ITALIC = 30,
      TK_LABEL = 31,
      TK_LANGUAGE = 16,
      TK_NODE = 12,
      TK_OUTLINE = 17,
      TK_PACKAGE = 32,
      TK_PRESENTATION = 18,
      TK_REGULAR = 33,
      TK_STYLE = 9,
      TK_TEXT = 19,
      TK_TOKEN = 39,
      TK_UNDERLINE = 34,
      TK_EOF_TOKEN = 35,
      TK_COLON = 40,
      TK_IDENTIFIER = 1,
      TK_INTEGER = 36,
      TK_JAVA_EXPR = 20,
      TK_SINGLE_LINE_COMMENT = 41,
      TK_STRING_LITERAL = 21,
      TK_ERROR_TOKEN = 42;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "IDENTIFIER",
                 "LEFTBRACE",
                 "RIGHTBRACE",
                 "SEMICOLON",
                 "EQUAL",
                 "COLOR",
                 "FONT",
                 "ICON",
                 "STYLE",
                 "BOOLEAN",
                 "INT",
                 "NODE",
                 "DOT",
                 "COMMA",
                 "FOLDABLE",
                 "LANGUAGE",
                 "OUTLINE",
                 "PRESENTATION",
                 "TEXT",
                 "JAVA_EXPR",
                 "STRING_LITERAL",
                 "ARROW",
                 "LEFTPAREN",
                 "RIGHTPAREN",
                 "TIMES",
                 "BOLD",
                 "CASE",
                 "EXTENDS",
                 "IMPORT",
                 "ITALIC",
                 "LABEL",
                 "PACKAGE",
                 "REGULAR",
                 "UNDERLINE",
                 "EOF_TOKEN",
                 "INTEGER",
                 "PLUS",
                 "MINUS",
                 "TOKEN",
                 "COLON",
                 "SINGLE_LINE_COMMENT",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
